### ISSUE TITLE
Exceção ao gerar o modelo PRISM

### ISSUE THREAD

**Issue by Genaina** [lesunb/CRGMToPRISM#5]
java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.containsKey(TreeMap.java:232)
	at br.unb.cic.rtgoretoprism.generator.rtgore.RTGoreProducer.addGoal(RTGoreProducer.java:225)
	at br.unb.cic.rtgoretoprism.generator.rtgore.RTGoreProducer.run(RTGoreProducer.java:159)
	at br.unb.cic.rtgoretoprism.action.PRISMCodeGenerationAction.run(PRISMCodeGenerationAction.java:93)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)

**Comment by danilomendonca** [comment]
Please make sure to use the correct eclipse platform version.
