### ISSUE TITLE
Goals with names that don't follow the defined patterns cause problemas in PRISM model generations

### ISSUE THREAD

**Issue by gabrielsr** [lesunb/CRGMToPRISM#6]
How should bad named goals be handled? 

Even if a pattern are not visible in the model but present it causes the following error. 

Stracktrace 
java.lang.NullPointerException
	at br.unb.cic.rtgoretoprism.model.kl.RTContainer.compareTo(RTContainer.java:361)
	at br.unb.cic.rtgoretoprism.model.kl.RTContainer.compareTo(RTContainer.java:1)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:316)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:184)
	at java.util.Arrays.sort(Arrays.java:1246)
	at java.util.Arrays.sort(Arrays.java:1433)
	at java.util.List.sort(List.java:478)

**Comment by danilomendonca** [comment]
Good question. We may present a message informing the user of the malformated goal/task name.

Further improvements on how the framework deals with goals ids are welcome!
